### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by sibabalwe-qamata** [Sibabalwe-Qamata/waiter_webapp#3]
If one day is Selected it throws this Error:

TypeError: Cannot read property 'id' of undefined
    at getDayId (/home/coder/projects/waiter_webapp/waiters.js:54:41)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)

**Comment by sibabalwe-qamata** [comment]
need to add an Update function if the user exists in the database

**Comment by sibabalwe-qamata** [comment]
error: duplicate key value violates unique constraint "waiters_waiter_name_key"
